- capivaraprojects/greeneyes/models/Text.js
Attributes | Description
-- | --
id | Text ID
language | Language
tag | Tag identification
value | Text value
description | Description about text
> Convert Text Model

- capivaraprojects/greeneyes/models/BaseResponse.js
- capivaraprojects/greeneyes/models/Disease.js
- capivaraprojects/greeneyes/models/Image.js
- capivaraprojects/greeneyes/models/PagedResponse.js
- capivaraprojects/greeneyes/models/Plant.js
- capivaraprojects/greeneyes/models/Type.py
- capivaraprojects/greeneyes/models/User.js
- capivaraprojects/greeneyes/models/User.py
Create capivaraprojects.greeneyes.models in JS #9 
User model in JS and Python #8 
Type model in Python
> Create capivaraprojects.greeneyes.models in JS, User model in JS and Python and Type model in Python

- capivaraprojects/greeneyes/models/Type.py
- capivaraprojects/greeneyes/models/User.js
- capivaraprojects/greeneyes/models/User.py
Create User model  in JS and Python #8 
Create Type model in Python
> Create User (JS and Python) and Type (Python)

- capivaraprojects/greeneyes/database/Text.py
> Add Text ORM

- capivaraprojects/greeneyes/database/User.py
> add user ORM

- .gitmodules
- .travis.yml
- requirements.txt
Update models and database to create repository functions and fix #19
> Update submodules and do somethings from repository

- .travis.yml
- README.md
- api/gyresources/endpoints/BaseController.py
- api/gyresources/endpoints/PlantController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- api/restplus.py
- app.py
- requirements.txt
- tests/test_plant.py
Here I'm fixing issues:<br/>
:ballot_box_with_check: #51 <br/>
:ballot_box_with_check: #59 <br/>
:ballot_box_with_check: #54 <br/>
> GYResources to API

- api/gyresources/endpoints/BaseController.py
- api/gyresources/endpoints/PlantController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- tests/test_plant.py
In this pull request I've added some documentation to: 
✅  BaseController
✅  parsers
✅  serializers
I've changed:
✔️  PlantController - Unified controller
✔️  test_plant - update tests
> Add some documentation and unify PlantController

- api/gyresources/endpoints/TypeController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- app.py
- tests/test_type.py
> Add TypeController and test

- .travis.yml
- README.md
- api/gyresources/endpoints/ImageController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- app.py
- tests/test_image.py
Here I'm fixing #57 
And updating README
> Add ImageController and tests

- .travis.yml
- api/gyresources/endpoints/UserController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- app.py
- tests/test_user.py
> Add UserController and test

- api/gyresources/endpoints/DiseaseController.py
- api/gyresources/parsers.py
- api/gyresources/serializers.py
- app.py
- tests/test_disease.py
> add disease controller

- .travis.yml
- tests/test_disease.py
> Add logger, update test

- .landscape.yml
- .travis.yml
- api/gyresources/endpoints/PlantController.py
- tests/test_plant.py
> Add plant missing tests

- .landscape.yml
- .travis.yml
- api/gyresources/endpoints/TypeController.py
- api/gyresources/endpoints/UserController.py
- api/restplus.py
- setup.py
- tests/test_1user.py
- tests/test_type.py
> fix landscape config and TypeController coverage

- .travis.yml
- api/gyresources/endpoints/BaseController.py
- api/gyresources/endpoints/DiseaseController.py
- api/gyresources/endpoints/ImageController.py
- api/gyresources/endpoints/LoggerController.py
- api/gyresources/endpoints/PlantController.py
- api/gyresources/endpoints/TextController.py
- api/gyresources/endpoints/TypeController.py
- api/gyresources/endpoints/UserController.py
- api/gyresources/endpoints/token.py
- api/restplus.py
- config.py
- tests/test_1user.py
- tests/test_type.py
> Install elasticsearch on Travis OSX

- .env
- Dockerfile
- api/gyresources/endpoints/BaseController.py
- api/gyresources/endpoints/DiseaseController.py
- api/gyresources/endpoints/ImageController.py
- api/gyresources/endpoints/LoggerController.py
- api/gyresources/endpoints/PlantController.py
- api/gyresources/endpoints/TextController.py
- api/gyresources/endpoints/TypeController.py
- api/gyresources/endpoints/UserController.py
- api/gyresources/endpoints/token.py
- config.py
- docker-compose.test.yml
- tests/test_type.py
Here I'm adding elasticsearch for #94
> add elastic search #94

- README.md
Update README adding docker badge
> add docker badge

- api/gyresources/endpoints/AnalysisController.py
- api/gyresources/logic/analysisResultParallelThread.py
- config.py
- requirements.txt
I'm adding some things needed to analysis
> Prepare analysis for crops

- app.py
- config.py
I'm changing configurations to able GYResources to be detected by network
> Put GYResources to run on 5000

- .travis.yml
- api/gyresources/endpoints/AnalysisController.py
- api/gyresources/endpoints/PlantController.py
- api/gyresources/logic/tf_serving_client.py
I've replaced disease search db on make_prediction to a search on a list of diseases and removed osx from travis
> Reduce prediction time

- Dockerfile
- execute.sh
I'm adding RabbitMQ dependency and Celery on Dockerfile
> Add some dependencies to dockerfile

- Dockerfile
- api/gyresources/endpoints/AnalysisController.py
- api/gyresources/parsers.py
- docker-compose.test.yml
- execute.sh
- tests/test_analysis.py
I'm adding the option to Analysis read results and write some rectangles on main image
> Add read function on Analysis

- api/gyresources/endpoints/TextController.py
Added attributes Plant, Status, Attribute and Reference.
Removed attributes Tag and Description.
Indent code.
> Fix controller class TextController
